_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /adminarea
portfolio:
    resource: "@PhotographyBundle/Resources/config/routing.yml"
    prefix:   /
