security:
    providers:
        asphotography_admins:
            entity: { class: ASPhotography\AdminBundle\Entity\AdminUser, property: username }
    encoders:
        ASPhotography\AdminBundle\Entity\AdminUser:
            algorithm: sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_USER ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        asphotography_admin_area:
            pattern: ^/adminarea
            anonymous:  ~
            provider: asphotography_admins
            form_login:
                login_path: asphotography_admin_login
                check_path: asphotography_admin_login_check
                default_target_path: asphotography_admin_dashboard
                always_use_default_target_path: true
            logout:
                path:   asphotography_admin_logout
                target: asphotography_admin_login
                invalidate_session: true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /adminarea
                domain:   ~
        asphotography_site_area:
            pattern: ^/
            anonymous:  ~
    access_control:
        - { path: ^/adminarea/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adminarea, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }